// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/v1/user/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Admin         bool                   `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_v1_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_v1_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type UserInternal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Admin         bool                   `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInternal) Reset() {
	*x = UserInternal{}
	mi := &file_proto_v1_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInternal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInternal) ProtoMessage() {}

func (x *UserInternal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInternal.ProtoReflect.Descriptor instead.
func (*UserInternal) Descriptor() ([]byte, []int) {
	return file_proto_v1_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInternal) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInternal) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInternal) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInternal) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type UserReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReference) Reset() {
	*x = UserReference{}
	mi := &file_proto_v1_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReference) ProtoMessage() {}

func (x *UserReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReference.ProtoReflect.Descriptor instead.
func (*UserReference) Descriptor() ([]byte, []int) {
	return file_proto_v1_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserReference) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_proto_v1_user_user_proto protoreflect.FileDescriptor

const file_proto_v1_user_user_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/user/user.proto\x12\x02v1\"B\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05admin\x18\x03 \x01(\bR\x05admin\"f\n" +
	"\fUserInternal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05admin\x18\x04 \x01(\bR\x05admin\"(\n" +
	"\rUserReference\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userIdB\x16Z\x14proto/v1/user;userv1b\x06proto3"

var (
	file_proto_v1_user_user_proto_rawDescOnce sync.Once
	file_proto_v1_user_user_proto_rawDescData []byte
)

func file_proto_v1_user_user_proto_rawDescGZIP() []byte {
	file_proto_v1_user_user_proto_rawDescOnce.Do(func() {
		file_proto_v1_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_user_user_proto_rawDesc), len(file_proto_v1_user_user_proto_rawDesc)))
	})
	return file_proto_v1_user_user_proto_rawDescData
}

var file_proto_v1_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_user_user_proto_goTypes = []any{
	(*User)(nil),          // 0: v1.User
	(*UserInternal)(nil),  // 1: v1.UserInternal
	(*UserReference)(nil), // 2: v1.UserReference
}
var file_proto_v1_user_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_v1_user_user_proto_init() }
func file_proto_v1_user_user_proto_init() {
	if File_proto_v1_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_user_user_proto_rawDesc), len(file_proto_v1_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_user_user_proto_goTypes,
		DependencyIndexes: file_proto_v1_user_user_proto_depIdxs,
		MessageInfos:      file_proto_v1_user_user_proto_msgTypes,
	}.Build()
	File_proto_v1_user_user_proto = out.File
	file_proto_v1_user_user_proto_goTypes = nil
	file_proto_v1_user_user_proto_depIdxs = nil
}
