// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/v1/cart/cart.proto

package cartv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookIds       []int64                `protobuf:"varint,1,rep,packed,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartData) Reset() {
	*x = CartData{}
	mi := &file_proto_v1_cart_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartData) ProtoMessage() {}

func (x *CartData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cart_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartData.ProtoReflect.Descriptor instead.
func (*CartData) Descriptor() ([]byte, []int) {
	return file_proto_v1_cart_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartData) GetBookIds() []int64 {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type UpdateCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cart          *CartData              `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartRequest) Reset() {
	*x = UpdateCartRequest{}
	mi := &file_proto_v1_cart_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartRequest) ProtoMessage() {}

func (x *UpdateCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cart_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartRequest.ProtoReflect.Descriptor instead.
func (*UpdateCartRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartRequest) GetCart() *CartData {
	if x != nil {
		return x.Cart
	}
	return nil
}

type UpdateCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cart          *CartData              `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCartResponse) Reset() {
	*x = UpdateCartResponse{}
	mi := &file_proto_v1_cart_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCartResponse) ProtoMessage() {}

func (x *UpdateCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cart_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCartResponse.ProtoReflect.Descriptor instead.
func (*UpdateCartResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCartResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCartResponse) GetCart() *CartData {
	if x != nil {
		return x.Cart
	}
	return nil
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_proto_v1_cart_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cart_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *CheckoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_proto_v1_cart_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_cart_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *CheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_v1_cart_cart_proto protoreflect.FileDescriptor

const file_proto_v1_cart_cart_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/cart/cart.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\"%\n" +
	"\bCartData\x12\x19\n" +
	"\bbook_ids\x18\x01 \x03(\x03R\abookIds\"N\n" +
	"\x11UpdateCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\x04cart\x18\x02 \x01(\v2\f.v1.CartDataR\x04cart\"O\n" +
	"\x12UpdateCartResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\x04cart\x18\x02 \x01(\v2\f.v1.CartDataR\x04cart\"*\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\",\n" +
	"\x10CheckoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xaf\x01\n" +
	"\vCartService\x12P\n" +
	"\n" +
	"UpdateCart\x12\x15.v1.UpdateCartRequest\x1a\x16.v1.UpdateCartResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/cart\x12N\n" +
	"\bCheckout\x12\x13.v1.CheckoutRequest\x1a\x14.v1.CheckoutResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/checkoutB\x17Z\x15proto/v1/cart; cartv1b\x06proto3"

var (
	file_proto_v1_cart_cart_proto_rawDescOnce sync.Once
	file_proto_v1_cart_cart_proto_rawDescData []byte
)

func file_proto_v1_cart_cart_proto_rawDescGZIP() []byte {
	file_proto_v1_cart_cart_proto_rawDescOnce.Do(func() {
		file_proto_v1_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_cart_cart_proto_rawDesc), len(file_proto_v1_cart_cart_proto_rawDesc)))
	})
	return file_proto_v1_cart_cart_proto_rawDescData
}

var file_proto_v1_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_cart_cart_proto_goTypes = []any{
	(*CartData)(nil),           // 0: v1.CartData
	(*UpdateCartRequest)(nil),  // 1: v1.UpdateCartRequest
	(*UpdateCartResponse)(nil), // 2: v1.UpdateCartResponse
	(*CheckoutRequest)(nil),    // 3: v1.CheckoutRequest
	(*CheckoutResponse)(nil),   // 4: v1.CheckoutResponse
}
var file_proto_v1_cart_cart_proto_depIdxs = []int32{
	0, // 0: v1.UpdateCartRequest.cart:type_name -> v1.CartData
	0, // 1: v1.UpdateCartResponse.cart:type_name -> v1.CartData
	1, // 2: v1.CartService.UpdateCart:input_type -> v1.UpdateCartRequest
	3, // 3: v1.CartService.Checkout:input_type -> v1.CheckoutRequest
	2, // 4: v1.CartService.UpdateCart:output_type -> v1.UpdateCartResponse
	4, // 5: v1.CartService.Checkout:output_type -> v1.CheckoutResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_cart_cart_proto_init() }
func file_proto_v1_cart_cart_proto_init() {
	if File_proto_v1_cart_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_cart_cart_proto_rawDesc), len(file_proto_v1_cart_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_cart_cart_proto_goTypes,
		DependencyIndexes: file_proto_v1_cart_cart_proto_depIdxs,
		MessageInfos:      file_proto_v1_cart_cart_proto_msgTypes,
	}.Build()
	File_proto_v1_cart_cart_proto = out.File
	file_proto_v1_cart_cart_proto_goTypes = nil
	file_proto_v1_cart_cart_proto_depIdxs = nil
}
