// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/v1/book/book.proto

package bookv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    int32                  `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookData) Reset() {
	*x = BookData{}
	mi := &file_proto_v1_book_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookData) ProtoMessage() {}

func (x *BookData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookData.ProtoReflect.Descriptor instead.
func (*BookData) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookData) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BookData) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookData) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BookData) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *BookData) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *BookData              `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_proto_v1_book_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookRequest) GetBook() *BookData {
	if x != nil {
		return x.Book
	}
	return nil
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          *BookData              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_proto_v1_book_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateBookResponse) GetBook() *BookData {
	if x != nil {
		return x.Book
	}
	return nil
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_proto_v1_book_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          *BookData              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_proto_v1_book_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBookResponse) GetBook() *BookData {
	if x != nil {
		return x.Book
	}
	return nil
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          *BookData              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_proto_v1_book_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookRequest) GetBook() *BookData {
	if x != nil {
		return x.Book
	}
	return nil
}

type UpdateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          *BookData              `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_proto_v1_book_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookResponse) GetBook() *BookData {
	if x != nil {
		return x.Book
	}
	return nil
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_proto_v1_book_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBookRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_proto_v1_book_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    []int32                `protobuf:"varint,1,rep,packed,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksRequest) Reset() {
	*x = ListBooksRequest{}
	mi := &file_proto_v1_book_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksRequest) ProtoMessage() {}

func (x *ListBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksRequest.ProtoReflect.Descriptor instead.
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{9}
}

func (x *ListBooksRequest) GetCategoryId() []int32 {
	if x != nil {
		return x.CategoryId
	}
	return nil
}

func (x *ListBooksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*CreateBookResponse  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBooksResponse) Reset() {
	*x = ListBooksResponse{}
	mi := &file_proto_v1_book_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBooksResponse) ProtoMessage() {}

func (x *ListBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_book_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBooksResponse.ProtoReflect.Descriptor instead.
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_book_book_proto_rawDescGZIP(), []int{10}
}

func (x *ListBooksResponse) GetBooks() []*CreateBookResponse {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_proto_v1_book_book_proto protoreflect.FileDescriptor

const file_proto_v1_book_book_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/book/book.proto\x12\x02v1\x1a\x1cgoogle/api/annotations.proto\"\x99\x01\n" +
	"\bBookData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x05R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x05R\n" +
	"categoryId\"5\n" +
	"\x11CreateBookRequest\x12 \n" +
	"\x04book\x18\x01 \x01(\v2\f.v1.BookDataR\x04book\"F\n" +
	"\x12CreateBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04book\x18\x02 \x01(\v2\f.v1.BookDataR\x04book\" \n" +
	"\x0eGetBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x0fGetBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04book\x18\x02 \x01(\v2\f.v1.BookDataR\x04book\"E\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04book\x18\x02 \x01(\v2\f.v1.BookDataR\x04book\"F\n" +
	"\x12UpdateBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x04book\x18\x02 \x01(\v2\f.v1.BookDataR\x04book\"#\n" +
	"\x11DeleteBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\".\n" +
	"\x12DeleteBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x10ListBooksRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x03(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"A\n" +
	"\x11ListBooksResponse\x12,\n" +
	"\x05books\x18\x01 \x03(\v2\x16.v1.CreateBookResponseR\x05books2\xa2\x03\n" +
	"\vBookService\x12P\n" +
	"\n" +
	"CreateBook\x12\x15.v1.CreateBookRequest\x1a\x16.v1.CreateBookResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/book\x12I\n" +
	"\aGetBook\x12\x12.v1.GetBookRequest\x1a\x13.v1.GetBookResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/book/{id}\x12U\n" +
	"\n" +
	"UpdateBook\x12\x15.v1.UpdateBookRequest\x1a\x16.v1.UpdateBookResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*2\r/v1/book/{id}\x12R\n" +
	"\n" +
	"DeleteBook\x12\x15.v1.DeleteBookRequest\x1a\x16.v1.DeleteBookResponse\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/book/{id}\x12K\n" +
	"\tListBooks\x12\x14.v1.ListBooksRequest\x1a\x15.v1.ListBooksResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/booksB\x17Z\x15proto/v1/book; bookv1b\x06proto3"

var (
	file_proto_v1_book_book_proto_rawDescOnce sync.Once
	file_proto_v1_book_book_proto_rawDescData []byte
)

func file_proto_v1_book_book_proto_rawDescGZIP() []byte {
	file_proto_v1_book_book_proto_rawDescOnce.Do(func() {
		file_proto_v1_book_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_book_book_proto_rawDesc), len(file_proto_v1_book_book_proto_rawDesc)))
	})
	return file_proto_v1_book_book_proto_rawDescData
}

var file_proto_v1_book_book_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_book_book_proto_goTypes = []any{
	(*BookData)(nil),           // 0: v1.BookData
	(*CreateBookRequest)(nil),  // 1: v1.CreateBookRequest
	(*CreateBookResponse)(nil), // 2: v1.CreateBookResponse
	(*GetBookRequest)(nil),     // 3: v1.GetBookRequest
	(*GetBookResponse)(nil),    // 4: v1.GetBookResponse
	(*UpdateBookRequest)(nil),  // 5: v1.UpdateBookRequest
	(*UpdateBookResponse)(nil), // 6: v1.UpdateBookResponse
	(*DeleteBookRequest)(nil),  // 7: v1.DeleteBookRequest
	(*DeleteBookResponse)(nil), // 8: v1.DeleteBookResponse
	(*ListBooksRequest)(nil),   // 9: v1.ListBooksRequest
	(*ListBooksResponse)(nil),  // 10: v1.ListBooksResponse
}
var file_proto_v1_book_book_proto_depIdxs = []int32{
	0,  // 0: v1.CreateBookRequest.book:type_name -> v1.BookData
	0,  // 1: v1.CreateBookResponse.book:type_name -> v1.BookData
	0,  // 2: v1.GetBookResponse.book:type_name -> v1.BookData
	0,  // 3: v1.UpdateBookRequest.book:type_name -> v1.BookData
	0,  // 4: v1.UpdateBookResponse.book:type_name -> v1.BookData
	2,  // 5: v1.ListBooksResponse.books:type_name -> v1.CreateBookResponse
	1,  // 6: v1.BookService.CreateBook:input_type -> v1.CreateBookRequest
	3,  // 7: v1.BookService.GetBook:input_type -> v1.GetBookRequest
	5,  // 8: v1.BookService.UpdateBook:input_type -> v1.UpdateBookRequest
	7,  // 9: v1.BookService.DeleteBook:input_type -> v1.DeleteBookRequest
	9,  // 10: v1.BookService.ListBooks:input_type -> v1.ListBooksRequest
	2,  // 11: v1.BookService.CreateBook:output_type -> v1.CreateBookResponse
	4,  // 12: v1.BookService.GetBook:output_type -> v1.GetBookResponse
	6,  // 13: v1.BookService.UpdateBook:output_type -> v1.UpdateBookResponse
	8,  // 14: v1.BookService.DeleteBook:output_type -> v1.DeleteBookResponse
	10, // 15: v1.BookService.ListBooks:output_type -> v1.ListBooksResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_v1_book_book_proto_init() }
func file_proto_v1_book_book_proto_init() {
	if File_proto_v1_book_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_book_book_proto_rawDesc), len(file_proto_v1_book_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_book_book_proto_goTypes,
		DependencyIndexes: file_proto_v1_book_book_proto_depIdxs,
		MessageInfos:      file_proto_v1_book_book_proto_msgTypes,
	}.Build()
	File_proto_v1_book_book_proto = out.File
	file_proto_v1_book_book_proto_goTypes = nil
	file_proto_v1_book_book_proto_depIdxs = nil
}
